(package-initialize)
(setq-default cursor-type 'bar)
(setq inhibit-splash-screen t)
(setq make-backup-files nil)
(menu-bar-mode -1)
(tool-bar-mode -1)
(delete-selection-mode 1)
(scroll-bar-mode -1)
(global-linum-mode 1)

(when (member "Cascadia Code" (font-family-list))
  (set-face-attribute 'default nil :font "Cascadia Code-10"))
(provide 'init-ui)
